//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.SCCI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PE.SCCI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication exception: {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Communication_exception {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Communication_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication exception: hardware timeout.
        /// </summary>
        internal static string SCCIMasterAdapter_Communication_exception_hardware_timeout {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Communication_exception_hardware_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error: timeout while reading data stream.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_data_stream {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_data_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error: timeout while reading frame body.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_frame_body {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_frame_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error: timeout while reading frame header.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_frame_header {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_frame_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: bad CRC - received {0}, computed {1}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_bad_CRC {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_bad_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: invalid value in field FUNCTION: 0x{0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_invalid_value_in_field {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_invalid_value_in_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: wrong node ID {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_node_ID {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_node_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: wrong RR bit.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_RR_bit {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_RR_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser error: wrong START byte {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_START_byte {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_START_byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response is not matched to request: request - {0}:{1}, response - {2}:{3}.
        /// </summary>
        internal static string SCCIMasterAdapter_Response_is_not_matched_to_request {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Response_is_not_matched_to_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCCI protocol error: code - {0}, details - {1}.
        /// </summary>
        internal static string SCCIMasterAdapter_SCCI_protocol_error {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_SCCI_protocol_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming mode hasn&apos;t been enabled.
        /// </summary>
        internal static string SCCIMasterAdapter_Streaming_mode_hasnt_been_enabled {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Streaming_mode_hasnt_been_enabled", resourceCulture);
            }
        }
    }
}
