//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.SCCI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PE.SCCI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communication exception: {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Communication_exception {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Communication_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communication exception: hardware timeout.
        /// </summary>
        internal static string SCCIMasterAdapter_Communication_exception_hardware_timeout {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Communication_exception_hardware_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General error: timeout while reading data stream.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_data_stream {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_data_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General error: timeout while reading frame body.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_frame_body {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_frame_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General error: timeout while reading frame header.
        /// </summary>
        internal static string SCCIMasterAdapter_General_error_timeout_while_reading_frame_header {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_General_error_timeout_while_reading_frame_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parser error: bad CRC - received {0}, computed {1}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_bad_CRC {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_bad_CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parser error: invalid value in field FUNCTION: 0x{0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_invalid_value_in_field {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_invalid_value_in_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parser error: wrong node ID {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_node_ID {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_node_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parser error: wrong RR bit.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_RR_bit {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_RR_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parser error: wrong START byte {0}.
        /// </summary>
        internal static string SCCIMasterAdapter_Parser_error_wrong_START_byte {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Parser_error_wrong_START_byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Response is not matched to request: request - {0}:{1}, response - {2}:{3}.
        /// </summary>
        internal static string SCCIMasterAdapter_Response_is_not_matched_to_request {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Response_is_not_matched_to_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SCCI protocol error: code - {0}, details - {1}.
        /// </summary>
        internal static string SCCIMasterAdapter_SCCI_protocol_error {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_SCCI_protocol_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streaming mode hasn&apos;t been enabled.
        /// </summary>
        internal static string SCCIMasterAdapter_Streaming_mode_hasnt_been_enabled {
            get {
                return ResourceManager.GetString("SCCIMasterAdapter_Streaming_mode_hasnt_been_enabled", resourceCulture);
            }
        }
    }
}
